Qshop/Buyer/urls.py
from .views import  *
from django.urls import path,re_path,include
urlpatterns = [
path("index/",index),
path("register/",register),
path("login/",login),
path("logout/",logout),
path("base/",base),
path("goods_list/",goods_list),
path("goods_detail/",goods_detail),
path("place_order/",place_order),
path("gettest/",gettest),
path("goods_test/",goods_test),
path("pay_result/",pay_result),
path("alipay_order/",alipay_order),
path("cart/",cart),
path("add_cart/",add_cart),
path("change_cart/",change_cart),
path("user_center_info/",user_center_info),
path("user_center_order/",user_center_order),
path("user_center_site/",user_center_site),
path("update_useraddress/",update_useraddress),
path("cart_place_order/",cart_place_order),

]

Qshop/Qshop/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from Buyer.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path("seller/",include("Seller.urls")),
    path("buyer/",include("Buyer.urls")),
    re_path("^$",index),
    path("login/",login),
    path("register/",register),
    ]

Qshop/Buyer/models.py
from django.db import models
from Seller.models import LoginUser,Goods

# Create your models here.
ORDER_STATUS = (
    (1,"未支付"),
    (2,"已支付"),
    (3,"待发货"),
    (4,"已发货"),
    (5,"拒收"),
    (6,"已完成"),
)


class PayOrder(models.Model):
    order_number=models.CharField(max_length=36,unique=True,verbose_name="订单号")
    order_date=models.DateField(auto_now=True,verbose_name="订单创建时间")
    order_status=models.IntegerField(choices=ORDER_STATUS,verbose_name="订单状态")
    order_total=models.FloatField(verbose_name="订单总价")
    order_user=models.ForeignKey(to=LoginUser,on_delete=models.CASCADE,verbose_name="买家")
    class Meta:
        db_table="pay_order"

class OrderInfo(models.Model):
    order = models.ForeignKey(to=PayOrder,on_delete=models.CASCADE)
    goods = models.ForeignKey(to=Goods, on_delete=models.CASCADE)
    goods_price = models.FloatField(verbose_name="商品的单价")
    store = models.ForeignKey(to=LoginUser, on_delete=models.CASCADE, verbose_name="卖家")
    goods_count = models.IntegerField(verbose_name="购买的单品的数量")
    goods_total_price = models.FloatField(verbose_name="购买的单品的总金额")

    class Meta:
        db_table = "order_info"





class Cart(models.Model):
    goods = models.ForeignKey(to=Goods,on_delete=models.CASCADE)
    goods_number = models.IntegerField(verbose_name="商品的数量")
    goods_total = models.FloatField(verbose_name="商品的小计")
    # goods_price = models.FloatField()
    cart_user = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE,verbose_name="买家")
    class Meta:

        db_table = "cart"


class UserAddress(models.Model):
    name = models.CharField(max_length=32,verbose_name="收货人姓名")
    phone = models.CharField(max_length=11,verbose_name="收货人手机号")
    address = models.TextField(verbose_name="收货人手机号")
    user = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE)
    status = models.IntegerField(verbose_name="地址状态",default=0)  ### 1

class PayorderAddress(models.Model):
    name = models.CharField(max_length=32,verbose_name="收货人姓名")
    phone = models.CharField(max_length=11,verbose_name="收货人手机号")
    address= models.TextField(verbose_name="收货人地址")
    payorder=models.OneToOneField(to=PayOrder,on_delete=models.CASCADE)

Qshop/Buyer/views.py
from django.shortcuts import render
import hashlib
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from Seller.models import *
from .models import *
from django .db.models import Sum,Count,Max,Min,Avg
from Qshop.settings import alipay
# Create your views here.
def setPassword(password):
    md5=hashlib.md5()
    md5.update(password.encode())
    result=md5.hexdigest()
    return result

## 登录装饰器
def loginValid(func):
    def inner(request,*args,**kwargs):
        ##校验登录
        cookie_email = request.COOKIES.get("buy_email")
        session_email = request.session.get("buy_email")
        if cookie_email and session_email and cookie_email == session_email:
            flag = LoginUser.objects.filter(email=cookie_email,id=request.COOKIES.get("buy_userid"),user_type=1).exists()
            if flag:
                return func(request,*args,**kwargs)
            else:
                return HttpResponseRedirect("/login/")
        else:
            return HttpResponseRedirect("/login/")
    return inner
# def loginValid(func):
#     def inner(request,*args,**kwargs):
#         cookie_email=request.COOKIES.get("buy_email")
#         session_email=request.session.get("buy_email")
#         if cookie_email and session_email and cookie_email == session_email:
#             return func(request,*args,**kwargs)
#         else:
#             return HttpResponseRedirect("/login/")
#     return  inner

def register(request):
    if request.method == "POST":
        # print(request.POST)
        username=request.POST.get("user_name")
        password=request.POST.get("pwd")
        repassword = request.POST.get("cpwd")
        email = request.POST.get("email")
        if email and password and password ==repassword:
            LoginUser.objects.create(email=email,password=setPassword(password),username= username)
            return HttpResponseRedirect("/login/")
        else:
            message="参数为空"
    return render(request,"buyer/register.html")

def login(request):
    if request.method=="POST":
        print(request.POST)
        username = request.POST.get("username")
        password = request.POST.get("pwd")
        if username and password:
             user=LoginUser.objects.filter(username=username,password=setPassword(password),user_type=1).first()
             if user:
                 response=HttpResponseRedirect("/")
                 response.set_cookie("buy_email",user.email)
                 response.set_cookie("buy_username", user.username)
                 response.set_cookie("buy_userid",user.id)
            # 区别：response用于设置cookie   request 用于设置session
            #      request.session["buy_username"]=user.username
                 request.session["buy_email"] = user.email

                 return  response
             else:
                 message="账号密码不正确"
        else:
             message="信息为空"

    return render(request, "buyer/login.html",locals())

#
@loginValid
def index(request):
    goods_type=GoodsType.objects.all()
    print((goods_type))
    # res = [{"type": "新鲜水果.obj", "goods": [goods1, goods2, goods3, goods4]}, {}, {}]
    res=[]
    for one in goods_type:
        print(one)
        goods = one.goods_set.order_by("id").all()
        if len(goods) > 4:
            goods_list = goods[:4]
            res.append({"type": one, "goods_list": goods_list})
        elif len(goods) > 0 and len(goods) <= 4:
            goods_list = goods
            res.append({"type": one, "goods_list": goods_list})
        print(res)

    return render(request, "buyer/index.html",locals())


def logout(request):
    resp = HttpResponseRedirect("/login/")
    resp.delete_cookie("buy_email")
    resp.delete_cookie("buy_username")
    resp.delete_cookie("buy_userid")
    del request.session["buy_email"]
    return resp


def base(request):
    return render(request,"buyer/base.html")


def goods_list(request):
    kywards=request.GET.get("kywards")
    req_type=request.GET.get("req_type")
    if req_type=="find_all":
         goods_type=GoodsType.objects.filter(id=int(kywards)).first()
         goods=goods_type.goods_set.order_by("-goods_pro_time")
         print(goods)
    else:
        goods = Goods.objects.filter(goods_name__contains=kywards).order_by("-goods_pro_time")
    goods_new=goods[:2]
    return render(request,"buyer/goods_list.html",locals())


def goods_detail(request):
    ##    此方法好使   后边加  通过商品的i?goods_id=1d 获取商品 或者get 改为filter
    goods_id = request.GET.get("goods_id")
    goods = Goods.objects.get(id=int( goods_id))
    return render(request,"buyer/goods_detail.html",locals())

# uuid 唯一标识 作为id 几乎不会重复
def get_order_no():
    import uuid
    order_no=str(uuid.uuid4()).replace("-","")
    return order_no

@loginValid
def place_order(request):
    user_id=request.COOKIES.get("buy_userid")
    goods_id=request.GET.get("goods_id")
    goods_count= int(request.GET.get("goods_count"))
    goods = Goods.objects.get(id=goods_id)
    payorder = PayOrder()
    payorder.order_number=get_order_no()
    payorder.order_status =1
    payorder.order_total=goods_count *goods.goods_price
    payorder.order_user_id = int(user_id)
    payorder.save()




    order_info = OrderInfo()
    order_info.order = payorder
    order_info.goods = goods
    order_info.goods_price = goods.goods_price
    ## 店铺的信息 通过商品寻找 店铺
    order_info.store = goods.goods_store
    order_info.goods_count = goods_count
    order_info.goods_total_price = goods_count * goods.goods_price
    order_info.save()
    user_address=UserAddress.objects.filter(user_id=user_id,status=1).first()
    ## orderinfo
    return render(request, "buyer/place_order.html",locals())


def gettest(request):
    payorder=PayOrder.objects.get(id=1)
    order_info=payorder.orderinfor_set.first()
    goods=order_info.goods
    print(goods.goods_name)

    goods_name=payorder.orderinfor_set.first().goods.goods_name
    print (goods_name)


    return HttpResponse("test")

def goods_test(request):
    order_id = 1
    pay_order=PayOrder.objects.get(id=order_id)
    # 聚合方法aggregate  返回值 字典  key默认值  goods_count聚合方法
    sum_goods=pay_order.orderinfo_set.aggregate(Sum("goods_count"),
                                                mycount=Count("id"))
    return render(request,"buyer/goods_test.html",locals())



## 支付宝支付  应该对
@loginValid
def alipay_order(request):
    ## 获取订单  payorder _id
    payorder_id = request.GET.get("payorder_id")
    payorder = PayOrder.objects.get(id=payorder_id)
    user_id=request.COOKIES.get("buy_user_id")
    user_address = UserAddress.objects.filter(user_id=user_id,status=1).first()
    payorder_address=PayorderAddress.objects.create(address=user_address.address,
                                                    phone=user_address.phone,
                                                    payorder=payorder

    )
    # 3、 实例化一个订单
    order_string = alipay.api_alipay_trade_page_pay(
        subject="生鲜交易",  ## 主题
        out_trade_no= payorder.order_number,  ## 订单号
        total_amount= str(payorder.order_total),  ## 交易金额   字符串
        # return_url=None,  ##  回调的地址
        return_url="http://127.0.0.1:8000/buyer/pay_result/",
        notify_url=None  ## 通知
    )

    # 4、 返回支付宝支付的url
    result = "https://openapi.alipaydev.com/gateway.do?" + order_string
    return HttpResponseRedirect(result)


#应该对
def pay_result(request):
    out_trade_no = request.GET.get("out_trade_no")
    ## 修改订单的状态  未付款 -》 已付款
    payorder = PayOrder.objects.get(order_number=out_trade_no)
    payorder.order_status = 2
    payorder.save()

    return render(request,"buyer/pay_result.html",locals())


#貌似没毛病
@loginValid
def cart(request):
    user_id = request.COOKIES.get("buy_userid")
    cart = Cart.objects.filter(cart_user=LoginUser.objects.get(id=int(user_id))).all()

    ## 获取购物车中所有商品的 小计之和 以及 商品的数量之和
    ## 聚合  all_total 字典  key：vlaue  ->  {"sum_total":3232,"sum_number":3232}
    all_total = cart.aggregate(sum_total=Sum("goods_total"), sum_number=Sum("goods_number"))

    return render(request, "buyer/cart.html", locals())

#貌似没毛病
@loginValid
def add_cart(request):
    result = {"code":10000,"msg":"添加购物车成功"}
    data = request.POST
    ## 从cookie中获取买家
    user_id = request.COOKIES.get("buy_userid")
    print(data)
    goods_id = data.get("goods_id")
    goods_count = int(data.get("goods_count",1))  ## 商品详情页
    goods = Goods.objects.get(id = goods_id)

    ## 判断购物车中是否已经存在该商品
    cart = Cart.objects.filter(goods = goods).first()
    if cart:
        ## 存在
        cart.goods_number += goods_count
        # cart.goods_total = goods.goods_price * (goods_count + cart.goods_number)
        cart.goods_total += goods.goods_price * goods_count
    else:
        ## 不存在
        cart = Cart()
        cart.goods = goods
        cart.goods_number = goods_count
        cart.goods_total = goods_count * goods.goods_price
        cart.cart_user_id = user_id
    try:
        cart.save()
        result = {"code":10000,"msg":"添加购物车成功"}
    except:
        result = {"code": 10001, "msg": "添加购物车失败"}
    return JsonResponse(result)

# def change_cart(request):
#     result={"code":1111,"msg":"计算失败","data":{}}
#     data=request.POST
#     print(data)
#     cart_id=request.POST.get("cart_id")
#     js_type=request.POST.get("js_type")
#     if cart_id and js_type:
#        cart=Cart.objects.filter(id=int(cart_id)).first()
#     if js_type=="add":
#         cart.goods_number +=1
#         cart.goods_total
#     return JsonResponse(result)
#貌似/没毛病
def change_cart(request):
    result = {"code":10001,"msg":"计算失败","data":{}}
    ## 修改购物车的数量 以及小计
    ##   购物车id
    ## 操作的类型    add reduce

    data= request.POST
    print(data)
    cart_id = request.POST.get("cart_id")
    js_type = request.POST.get("js_type")
    if cart_id and js_type:
        cart = Cart.objects.filter(id = int(cart_id)).first()
        if cart:
            if js_type == "add":
                ## 加 操作
                cart.goods_number += 1
                cart.goods_total += cart.goods.goods_price

Qshop/Buyer/templates/buyer/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}天天生鲜-首页{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/main.css">
	<script type="text/javascript" src="/static/buyer/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/slide.js"></script>
{% block style %}

{% endblock %}
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>{{ request.COOKIES.buy_username }}</em>
				</div>
				<div class="login_btn fl">
                    {% if request.COOKIES.buy_username %}
                        <a href="#">{{ request.COOKIES.buy_username }}</a>
					    <span>|</span>
					    <a href="/buyer/logout/">退出</a>
                    {% else %}
                        <a href="/login/">登录</a>
					    <span>|</span>
					    <a href="/register/">注册</a>
                    {% endif %}

				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="/buyer/user_center_info/">用户中心</a>
					<span>|</span>
					<a href="/buyer/cart/">我的购物车</a>
					<span>|</span>
					<a href="/buyer/user_center_order/">我的订单</a>
				</div>
			</div>
		</div>
	</div>
    {% block search_bar %}
	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/buyer/images/logo.png"></a>
		<div class="search_con fl">
            <form action="/buyer/goods_list/">
                <input type="text" class="input_text fl" name="kywards" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="/buyer/cart/" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>
    {% endblock %}

    {% block content %}{% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	<script type="text/javascript" src="/static/buyer/js/slide.js"></script>
	<script type="text/javascript">
		//  BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		// oFruit.onclick = function(){
		// 	window.location.href = 'list.html';
		// }
	</script>
{% block script %}
{% endblock %}
</body>
</html>

Qshop/Buyer/templates/buyer/goods_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>
    统计订单下订单详情的状况
    {{ sum_goods }}
</p>
</body>
</html>

Qshop/Buyer/templates/buyer/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-登录</title>
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/main.css">
</head>
<body>
	<div class="login_top clearfix">
		<a href="/" class="login_logo"><img src="/static/buyer/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>

						<input type="submit" name="提交" value="登录" class="input_submit">
                        <a  href="/buyer/index/">s</a>
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

Qshop/Buyer/templates/buyer/pay_result.html
{% extends "buyer/base.html" %}

{% block content %}
{#    {{ request.GET }}#}
    {% for key,value in request.GET.items %}
        <p>
            {{ key }}:{{ value }}
        </p>
    {% endfor %}
{% endblock %}

Qshop/Buyer/templates/buyer/place_order.html
{% extends "buyer/base.html" %}
{% block title %}
    订单页面
{% endblock %}


{% block content %}
    	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="" checked="">{{ user_address.address }} （{{ user_address.name }} 收） {{ user_address.phone }}</dd>
		</dl>
		<a href="user_center_site.html" class="edit_site">编辑收货地址</a>

	</div>

	<h3 class="common_title">支付方式</h3>
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" >
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" checked>
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>

	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>
		</ul>
        {% for one_order_info in payorder.orderinfo_set.all %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>
			<li class="col02"><img src="/static/{{ one_order_info.goods.goods_picture }}"></li>
			<li class="col03">{{ one_order_info.goods.goods_name }}</li>
			<li class="col04">500g</li>
			<li class="col05">{{ one_order_info.goods.goods_price }}元</li>
			<li class="col06">{{ one_order_info.goods_count }}</li>
			<li class="col07">{{ one_order_info.goods_total_price }}元</li>
		</ul>
        {% endfor %}

	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ payorder.orderinfo_set.count }}</em>件商品，总金额<b>{{ payorder.order_total }}元</b></div>
			<div class="transit">运费：<b>10元</b></div>
			<div class="total_pay">实付款：<b>{{ payorder.order_total }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:;" id="order_btn">提交订单</a>
	</div>


{% endblock %}

{% block script %}
    <script>
        $("#order_btn").click(
            function () {
                // console.log(111111)
                var payorder_id = {{ payorder.id }};
                var url = "/buyer/alipay_order/?payorder_id=" + payorder_id;
                window.location.href = url;
            }
        )
    </script>
{% endblock %}

Qshop/Buyer/templates/buyer/register.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-注册</title>
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/main.css">
	<script type="text/javascript" src="/static/buyer/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/register.js"></script>
</head>
<body>
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/buyer/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

Qshop/Buyer/templates/buyer/user_center_order.html
{% extends "buyer/base.html" %}
{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/buyer/user_center_info/">· 个人信息</a></li>
				<li><a href="/buyer/user_center_order/" class="active">· 全部订单</a></li>
				<li><a href="/buyer/user_center_site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
                {% for payorderone in payorder_all %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ payorderone.order_date | date:"Y-m-d" }}</li>
                    <li class="col02 stress">{{ payorderone.get_order_status_display }}</li>
					<li class="col02" style="width: 300px;">订单号：{{ payorderone.order_number }}</li>

				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for orderinfoone in payorderone.orderinfo_set.all %}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="/static/{{ orderinfoone.goods.goods_picture }}"></li>
									<li class="col02">{{ orderinfoone.goods.goods_name }}<em>{{ orderinfoone.goods.goods_price }}元/500g</em></li>
									<li class="col03">{{ orderinfoone.goods_count }}</li>
									<li class="col04">{{ orderinfoone.goods_total_price }}元</li>
								</ul>
                                    {% endfor %}

							</td>
							<td width="15%">{{ payorderone.order_total }}元</td>
							<td width="15%">{{ payorderone.get_order_status_display }}</td>
							<td width="15%">
                                {% if payorderone.order_status == 1 %}
                                    <a href="/buyer/alipay_order/?payorder_id={{ payorderone.id }}" class="oper_btn">去付款</a>
                                {% else %}
                                    <a href="#" class="oper_btn">查看物流</a>
                                {% endif %}
                            </td>
						</tr>
					</tbody>
				</table>
            {% endfor %}






				<div class="pagenation">
					<a href="#">上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>
{% endblock %}